### ISSUE TITLE
Ability to place/drag markers for source and destination

### ISSUE THREAD

**Issue by rKamindo** [rKamindo/pathfinding-visualizer#7]
**User Story**
As a user, I want to be able to click and place markers A and B, so that I can select the source and destination for pathfinding. The markers should snap to the node nearest where we click.

**Task list**
- [ ] create a function that asynchronously loads in node data by city
- [ ] initially build quadtree from node data based on the city
- [ ] implementing clicking to place start and end nodes
- [ ] implement dragging to drag start and end nodes
